### ISSUE TITLE
Does not set correct RPC port

### ISSUE THREAD

**Issue by Diablo-D3** [knotwork/old-devcoind#1]
Devcoin still tries to use port 8332 for RPC instead of 52332 (matching the 52333 data port), this means it cannot be started the same time as Bitcoin unless rpcport is set in ~/.devcoin/devcoin.conf

The port seems to be set in rpc.cpp:

```
rpc.cpp:    ip::tcp::endpoint endpoint(bindAddress, GetArg("-rpcport", 8332));
rpc.cpp:    if (!d.connect(GetArg("-rpcconnect", "127.0.0.1"), GetArg("-rpcport", "8332")))
rpc.cpp:    ip::tcp::iostream stream(GetArg("-rpcconnect", "127.0.0.1"), GetArg("-rpcport", "8332"));
```

**Comment by knotwork** [comment]
I guess I never noticed since I always set those ports explicitly and arbitrarily in my startup scripts. Thanks. I am due to put out a new release soon to use some new images so will change this while I am at it.

-MarkM-
